language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build stackone_hris_client.gemspec
  - gem install ./stackone_hris_client-1.2.2.gem
