generatorName: ruby
inputSpec: https://api.eu1.stackone.com/documentation-hris-yaml
additionalProperties:
  moduleName: "StackOneHRIS"
  gemAuthor: "StackOne"
  gemAuthorEmail: "developer-support@stackone.com"
  gemDescription: "StackOne Unified API client for enhanced integrations with HRIS systems"
  gemHomepage: "https://stackone.com"
  gemLicense: "MIT"
  gemName: "stackone_hris_client"
  gemRequiredRubyVersion: ">= 2.7"
  gemSummary: "StackOne HRIS client gem"
  gemVersion: "1.5.1"
  library: "typhoeus"
