=begin
#StackOne Unified API

#The documentation for the StackOne Unified API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for StackOneHrisClient::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = StackOneHrisClient::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(StackOneHrisClient::AccountsApi)
    end
  end

  # unit tests for accounts_get
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for accounts_list
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider The provider of the results to fetch
  # @option opts [String] :origin_owner_id The origin owner identifier of the results to fetch
  # @return [Array<Account>]
  describe 'accounts_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
