=begin
#StackOne Unified API - HRIS

#The documentation for the StackOne Unified API - HRIS

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for StackOneHRIS::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = StackOneHRIS::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(StackOneHRIS::AccountsApi)
    end
  end

  # unit tests for accounts_delete
  # Delete Account
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'accounts_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_get
  # Get Account
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_list
  # List Accounts
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider The provider of the results to fetch
  # @option opts [String] :origin_owner_id The origin owner identifier of the results to fetch
  # @return [Array<Account>]
  describe 'accounts_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_meta_get
  # Get meta information of the account
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [AccountMeta]
  describe 'accounts_meta_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
