=begin
#StackOne Unified API - HRIS

#The documentation for the StackOne Unified API - HRIS

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for StackOneHRIS::CompaniesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CompaniesApi' do
  before do
    # run before each test
    @api_instance = StackOneHRIS::CompaniesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompaniesApi' do
    it 'should create an instance of CompaniesApi' do
      expect(@api_instance).to be_instance_of(StackOneHRIS::CompaniesApi)
    end
  end

  # unit tests for hris_companies_get
  # Get Company
  # @param id 
  # @param x_account_id The account identifier
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page The page number of the results to fetch
  # @option opts [String] :page_size The number of results per page
  # @option opts [Boolean] :raw Indicates that the raw request result is returned
  # @option opts [String] :fields The comma separated list of fields to return in the response (if empty, all fields are returned)
  # @option opts [String] :sync_token The sync token to select the only updated results
  # @option opts [String] :updated_after Use a string with a date to only select results updated after that given date
  # @return [CompanyResult]
  describe 'hris_companies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hris_companies_list
  # List Companies
  # @param x_account_id The account identifier
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page The page number of the results to fetch
  # @option opts [String] :page_size The number of results per page
  # @option opts [Boolean] :raw Indicates that the raw request result is returned
  # @option opts [String] :fields The comma separated list of fields to return in the response (if empty, all fields are returned)
  # @option opts [String] :sync_token The sync token to select the only updated results
  # @option opts [String] :updated_after Use a string with a date to only select results updated after that given date
  # @return [CompaniesPaginated]
  describe 'hris_companies_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
