=begin
#StackOne Unified API

#The documentation for the StackOne Unified API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for StackOneHrisClient::EmployeesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmployeesApi' do
  before do
    # run before each test
    @api_instance = StackOneHrisClient::EmployeesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmployeesApi' do
    it 'should create an instance of EmployeesApi' do
      expect(@api_instance).to be_instance_of(StackOneHrisClient::EmployeesApi)
    end
  end

  # unit tests for employees_get
  # 
  # @param id 
  # @param x_account_id The account identifier
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page The page number of the results to fetch
  # @option opts [String] :page_size The number of results per page
  # @option opts [Boolean] :raw Indicates that the raw request result is returned
  # @option opts [Array<String>] :fields The list of fields to return in the response (if empty, all fields are returned)
  # @option opts [Array<String>] :expand The list of fields that will be expanded in the response
  # @return [Employee]
  describe 'employees_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for employees_list
  # 
  # @param x_account_id The account identifier
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page The page number of the results to fetch
  # @option opts [String] :page_size The number of results per page
  # @option opts [Boolean] :raw Indicates that the raw request result is returned
  # @option opts [Array<String>] :fields The list of fields to return in the response (if empty, all fields are returned)
  # @option opts [Array<String>] :expand The list of fields that will be expanded in the response
  # @return [Array<Employee>]
  describe 'employees_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
