=begin
#StackOne Unified API

#The documentation for the StackOne Unified API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StackOneHRIS::ConnectSessionAuthenticate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StackOneHRIS::ConnectSessionAuthenticate do
  let(:instance) { StackOneHRIS::ConnectSessionAuthenticate.new }

  describe 'test an instance of ConnectSessionAuthenticate' do
    it 'should create an instance of ConnectSessionAuthenticate' do
      expect(instance).to be_instance_of(StackOneHRIS::ConnectSessionAuthenticate)
    end
  end
  describe 'test attribute "token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
