=begin
#StackOne Unified API - HRIS

#The documentation for the StackOne Unified API - HRIS

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StackOneHRIS::EmployeeApiModelAvatar
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StackOneHRIS::EmployeeApiModelAvatar do
  let(:instance) { StackOneHRIS::EmployeeApiModelAvatar.new }

  describe 'test an instance of EmployeeApiModelAvatar' do
    it 'should create an instance of EmployeeApiModelAvatar' do
      expect(instance).to be_instance_of(StackOneHRIS::EmployeeApiModelAvatar)
    end
  end
  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "base64"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
