=begin
#StackOne Unified API

#The documentation for the StackOne Unified API

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StackOneHrisClient::EmployeesPaginated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StackOneHrisClient::EmployeesPaginated do
  let(:instance) { StackOneHrisClient::EmployeesPaginated.new }

  describe 'test an instance of EmployeesPaginated' do
    it 'should create an instance of EmployeesPaginated' do
      expect(instance).to be_instance_of(StackOneHrisClient::EmployeesPaginated)
    end
  end
  describe 'test attribute "next_page"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "raw"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
