=begin
#StackOne Unified API - HRIS

#The documentation for the StackOne Unified API - HRIS

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StackOneHRIS::EthnicityEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StackOneHRIS::EthnicityEnum do
  let(:instance) { StackOneHRIS::EthnicityEnum.new }

  describe 'test an instance of EthnicityEnum' do
    it 'should create an instance of EthnicityEnum' do
      expect(instance).to be_instance_of(StackOneHRIS::EthnicityEnum)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["white", "black_or_african_american", "asian", "hispanic_or_latino", "american_indian_or_alaska_native", "native_hawaiian_or_pacific_islander", "two_or_more_races", "not_disclosed", "other", "unmapped_value"])
      # validator.allowable_values.each do |value|
      #   expect { instance.value = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "source_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
